name: Pipeline CI/CD MLops

on:
  # 1. Agregamos 'push' para que corra cuando subes código
  push:
    branches: [ "dev", "main" ] 
  # 2. Mantenemos 'pull_request' por si acaso
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v4
      
      - name: SetUp Python
        # CORREGIDO: setup-python (no phyton)
        uses: actions/setup-python@v5 
        with:
          python-version: '3.12' # Recomiendo una versión estable. 3.14 puede no estar lista en Actions.
      
      - name: Install requirements
        # CORREGIDO: install (no intall)
        # OJO: Verifica si la carpeta en tu repo se llama 'phyton' o 'python'. 
        # Aquí asumo que corregiste el nombre a 'python'.
        run: pip install -r ./python/credit_scoring_DL/requirements.txt
      
      - name: Run tests 
        run: pytest ./python/credit_scoring_DL/tests/test_model_creation.py
