name: Pipeline CI/CD MLops

on:
  pull_request:
    branches: [dev]

jobs:
    build_and_test:
      runs-on: ubuntu-latest
      steps:
        - name : Check repository
          uses: actions/checkout@v4
          
        - name : SetUp Phyton
          uses: actions/setup-phyton@v5
          with:
            python-version : '3.14.2'
        - name : Install requirements
          run: pip intall -r ./python/credit_scoring_DL/requirements.txt
        - name : Run tests 
          run : pytest ./python/credit_scoring_DL/tests/test_model_creation.py 
